AUDIO_STATUS_DISABLED = "disabled"
AUDIO_STATUS_PENDING = "pending"
AUDIO_STATUS_RECORDING = "recording"
AUDIO_STATUS_READY = "ready"
AUDIO_STATUS_FAILED = "failed"

POSTPROCESS_STATUS_PENDING = "pending"
POSTPROCESS_STATUS_QUEUED = "queued"
POSTPROCESS_STATUS_BINDING_SOURCES = "binding_sources"
POSTPROCESS_STATUS_MATERIALIZING_AUDIO = "materializing_audio"
POSTPROCESS_STATUS_TRANSCRIBING_PARTICIPANTS = "transcribing_participants"
POSTPROCESS_STATUS_ASSEMBLING_SEGMENTS = "assembling_segments"
POSTPROCESS_STATUS_TRANSCRIBING = POSTPROCESS_STATUS_TRANSCRIBING_PARTICIPANTS
POSTPROCESS_STATUS_CANONICALIZING = POSTPROCESS_STATUS_BINDING_SOURCES
POSTPROCESS_STATUS_ALIGNING = POSTPROCESS_STATUS_BINDING_SOURCES
POSTPROCESS_STATUS_REBUILDING = POSTPROCESS_STATUS_ASSEMBLING_SEGMENTS
POSTPROCESS_STATUS_REVIEW_READY = "review_ready"
POSTPROCESS_STATUS_RUNNING = "running"
POSTPROCESS_STATUS_COMPLETED = "completed"
POSTPROCESS_STATUS_FAILED = "failed"

TRANSCRIPT_STATUS_ORIGINAL = "original"
TRANSCRIPT_STATUS_PENDING_REVIEW = "pending_review"
TRANSCRIPT_STATUS_AUTO_APPLIED = "auto_applied"
TRANSCRIPT_STATUS_ACCEPTED = "accepted"
TRANSCRIPT_STATUS_REJECTED = "rejected"

REVIEW_STATUS_PENDING = "pending"
REVIEW_STATUS_ACCEPTED = "accepted"
REVIEW_STATUS_REJECTED = "rejected"
REVIEW_STATUS_AUTO_APPLIED = "auto_applied"

ASSIGNMENT_STATUS_CONFIRMED = "confirmed"
ASSIGNMENT_STATUS_PROVISIONAL = "provisional"
ASSIGNMENT_STATUS_UNKNOWN = "unknown"
